[manager]

prepend_keymap = [
  { on = "<Esc>", run = "quit", desc = "Exit the process" },
  { on = [
    "'",
    ";",
  ], run = 'plugin custom-shell -- zsh --interactive', desc = "custom-shell as zsh, interactive" },
  { on = "o", run = "create", desc = "Create a file (ends with / for directories)" },
  { on = "t", run = [
    "select --state=none",
    "arrow 0",
  ], desc = "Toggle the current selection state" },
  { on = [
    "d",
    "d",
  ], run = "remove", desc = "Trash selected files" },
  { on = [
    "y",
    "y",
  ], run = "yank", desc = "Yank selected files (copy)" },
  { on = [
    "f",
    "f",
  ], run = "plugin fg --args='fzf'", desc = "find file by filename" },
  { on = [
    "f",
    "g",
  ], run = "plugin fg --args='rg'", desc = "find file by content (ripgrep match)" },

  { on = "p", run = "plugin toggle-pane max-preview", desc = "Maximize or restore preview" },

  { on = [
    "f",
    "r",
  ], run = "plugin fr rg", desc = "Search file by content (rg)" },

  { on = [
    "f",
    "a",
  ], run = "plugin fr rga", desc = "Search file by content (rga)" },

  { on = [
    "[",
    "\\",
  ], run = "shell \"open -a vlc $0\" --block", desc = "Run a shell command" },
  #Usage
  #Press c p to display the prompt.
  #Type any yazi command. e.g select_all
  #Parameters are assumed to be flags and default to the value "yes". e.g. yank --cut is equivalent to yank --cut=yes
  #Parameters can be assigned values either with an equals or a space. e.g. rename --empty=stem or rename --empty stem
  #Parameters can be assigned multiple arguments separated by a space. e.g. plugin example --args arg1 arg2 arg3
  #Multiple words that are NOT arguments should be placed in double quotes. e.g. shell "ls -l | less" --block --confirm
  #Argument values begining with -- are assumed to be arguments and should be escaped . e.g. use plugin shell --args=\--block
  #{ on   = [ "c", "p" ], run  = "plugin command", desc = "Yazi command prompt" },
  # { on = ["d", "u"], run = "plugin restore", desc = "Restore last deleted files/folders" },
  #{ on   = [ "i" ], run = "plugin searchjump -- autocd", desc = "searchjump mode" },
  # { on   = [ "c", "s"], run  = "plugin what-size", desc = "Calc size of selection or cwd" },
]

[[input.prepend_keymap]]
on = "o"
run = "open"
desc = "open dir"
